text = """
ar-EG* 	Female 	"Microsoft Server Speech Text to Speech Voice (ar-EG, Hoda)"
ar-SA 	Male 	"Microsoft Server Speech Text to Speech Voice (ar-SA, Naayf)"
ca-ES 	Female 	"Microsoft Server Speech Text to Speech Voice (ca-ES, HerenaRUS)"
cs-CZ 	Male 	"Microsoft Server Speech Text to Speech Voice (cs-CZ, Vit)"
da-DK 	Female 	"Microsoft Server Speech Text to Speech Voice (da-DK, HelleRUS)"
de-AT 	Male 	"Microsoft Server Speech Text to Speech Voice (de-AT, Michael)"
de-CH 	Male 	"Microsoft Server Speech Text to Speech Voice (de-CH, Karsten)"
de-DE 	Female 	"Microsoft Server Speech Text to Speech Voice (de-DE, Hedda) "
de-DE 	Female 	"Microsoft Server Speech Text to Speech Voice (de-DE, HeddaRUS)"
de-DE 	Male 	"Microsoft Server Speech Text to Speech Voice (de-DE, Stefan, Apollo) "
el-GR 	Male 	"Microsoft Server Speech Text to Speech Voice (el-GR, Stefanos)"
en-AU 	Female 	"Microsoft Server Speech Text to Speech Voice (en-AU, Catherine) "
en-AU 	Female 	"Microsoft Server Speech Text to Speech Voice (en-AU, HayleyRUS)"
en-CA 	Female 	"Microsoft Server Speech Text to Speech Voice (en-CA, Linda)"
en-CA 	Female 	"Microsoft Server Speech Text to Speech Voice (en-CA, HeatherRUS)"
en-GB 	Female 	"Microsoft Server Speech Text to Speech Voice (en-GB, Susan, Apollo)"
en-GB 	Female 	"Microsoft Server Speech Text to Speech Voice (en-GB, HazelRUS)"
en-GB 	Male 	"Microsoft Server Speech Text to Speech Voice (en-GB, George, Apollo)"
en-IE 	Male 	"Microsoft Server Speech Text to Speech Voice (en-IE, Shaun)"
en-IN 	Female 	"Microsoft Server Speech Text to Speech Voice (en-IN, Heera, Apollo)"
en-IN 	Female 	"Microsoft Server Speech Text to Speech Voice (en-IN, PriyaRUS)"
en-IN 	Male 	"Microsoft Server Speech Text to Speech Voice (en-IN, Ravi, Apollo)"
en-US 	Female 	"Microsoft Server Speech Text to Speech Voice (en-US, ZiraRUS)"
en-US 	Female 	"Microsoft Server Speech Text to Speech Voice (en-US, JessaRUS)"
en-US 	Male 	"Microsoft Server Speech Text to Speech Voice (en-US, BenjaminRUS)"
es-ES 	Female 	"Microsoft Server Speech Text to Speech Voice (es-ES, Laura, Apollo)"
es-ES 	Female 	"Microsoft Server Speech Text to Speech Voice (es-ES, HelenaRUS)"
es-ES 	Male 	"Microsoft Server Speech Text to Speech Voice (es-ES, Pablo, Apollo)"
es-MX 	Female 	"Microsoft Server Speech Text to Speech Voice (es-MX, HildaRUS)"
es-MX 	Male 	"Microsoft Server Speech Text to Speech Voice (es-MX, Raul, Apollo)"
fi-FI 	Female 	"Microsoft Server Speech Text to Speech Voice (fi-FI, HeidiRUS)"
fr-CA 	Female 	"Microsoft Server Speech Text to Speech Voice (fr-CA, Caroline)"
fr-CA 	Female 	"Microsoft Server Speech Text to Speech Voice (fr-CA, HarmonieRUS)"
fr-CH 	Male 	"Microsoft Server Speech Text to Speech Voice (fr-CH, Guillaume)"
fr-FR 	Female 	"Microsoft Server Speech Text to Speech Voice (fr-FR, Julie, Apollo)"
fr-FR 	Female 	"Microsoft Server Speech Text to Speech Voice (fr-FR, HortenseRUS)"
fr-FR 	Male 	"Microsoft Server Speech Text to Speech Voice (fr-FR, Paul, Apollo)"
he-IL 	Male 	"Microsoft Server Speech Text to Speech Voice (he-IL, Asaf)"
hi-IN 	Female 	"Microsoft Server Speech Text to Speech Voice (hi-IN, Kalpana, Apollo)"
hi-IN 	Female 	"Microsoft Server Speech Text to Speech Voice (hi-IN, Kalpana)"
hi-IN 	Male 	"Microsoft Server Speech Text to Speech Voice (hi-IN, Hemant)"
hu-HU 	Male 	"Microsoft Server Speech Text to Speech Voice (hu-HU, Szabolcs)"
id-ID 	Male 	"Microsoft Server Speech Text to Speech Voice (id-ID, Andika)"
it-IT 	Male 	"Microsoft Server Speech Text to Speech Voice (it-IT, Cosimo, Apollo)"
ja-JP 	Female 	"Microsoft Server Speech Text to Speech Voice (ja-JP, Ayumi, Apollo)"
ja-JP 	Male 	"Microsoft Server Speech Text to Speech Voice (ja-JP, Ichiro, Apollo)"
ja-JP 	Female 	"Microsoft Server Speech Text to Speech Voice (ja-JP, HarukaRUS)"
ja-JP 	Female 	"Microsoft Server Speech Text to Speech Voice (ja-JP, LuciaRUS)"
ja-JP 	Male 	"Microsoft Server Speech Text to Speech Voice (ja-JP, EkaterinaRUS)"
ko-KR 	Female 	"Microsoft Server Speech Text to Speech Voice (ko-KR, HeamiRUS)"
nb-NO 	Female 	"Microsoft Server Speech Text to Speech Voice (nb-NO, HuldaRUS)"
nl-NL 	Female 	"Microsoft Server Speech Text to Speech Voice (nl-NL, HannaRUS)"
pl-PL 	Female 	"Microsoft Server Speech Text to Speech Voice (pl-PL, PaulinaRUS)"
pt-BR 	Female 	"Microsoft Server Speech Text to Speech Voice (pt-BR, HeloisaRUS)"
pt-BR 	Male 	"Microsoft Server Speech Text to Speech Voice (pt-BR, Daniel, Apollo)"
pt-PT 	Female 	"Microsoft Server Speech Text to Speech Voice (pt-PT, HeliaRUS)"
ro-RO 	Male 	"Microsoft Server Speech Text to Speech Voice (ro-RO, Andrei)"
ru-RU 	Female 	"Microsoft Server Speech Text to Speech Voice (ru-RU, Irina, Apollo)"
ru-RU 	Male 	"Microsoft Server Speech Text to Speech Voice (ru-RU, Pavel, Apollo)"
sk-SK 	Male 	"Microsoft Server Speech Text to Speech Voice (sk-SK, Filip)"
sv-SE 	Female 	"Microsoft Server Speech Text to Speech Voice (sv-SE, HedvigRUS)"
th-TH 	Male 	"Microsoft Server Speech Text to Speech Voice (th-TH, Pattara)"
tr-TR 	Female 	"Microsoft Server Speech Text to Speech Voice (tr-TR, SedaRUS)"
zh-CN 	Female 	"Microsoft Server Speech Text to Speech Voice (zh-CN, HuihuiRUS)"
zh-CN 	Female 	"Microsoft Server Speech Text to Speech Voice (zh-CN, Yaoyao, Apollo)"
zh-CN 	Male 	"Microsoft Server Speech Text to Speech Voice (zh-CN, Kangkang, Apollo)"
zh-HK 	Female 	"Microsoft Server Speech Text to Speech Voice (zh-HK, Tracy, Apollo)"
zh-HK 	Female 	"Microsoft Server Speech Text to Speech Voice (zh-HK, TracyRUS)"
zh-HK 	Male 	"Microsoft Server Speech Text to Speech Voice (zh-HK, Danny, Apollo)"
zh-TW 	Female 	"Microsoft Server Speech Text to Speech Voice (zh-TW, Yating, Apollo)"
zh-TW 	Female 	"Microsoft Server Speech Text to Speech Voice (zh-TW, HanHanRUS)"
zh-TW 	Male 	"Microsoft Server Speech Text to Speech Voice (zh-TW, Zhiwei, Apollo)"
"""


def clean(vals):
    for i in range(3):
        vals[i] = vals[i].strip().replace('*', '').replace('"', '')
    return vals


def get_lang_dict():
    lang_dict = {}
    for i in text.splitlines()[1:-1]:
        vals = clean(i.split('\t'))
        if lang_dict.get(vals[0], None) == None:
            lang_dict[vals[0]] = {}
        lang_dict[vals[0]][vals[1]] = vals[2]
    return lang_dict
